# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Kmp Demo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'UIKit'

  target 'Kmp DemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Kmp DemoUITests' do
    # Pods for testing
  end
end
